
ALTER TABLE hannam_notices 
ADD COLUMN IF NOT EXISTS image_url TEXT,
ADD COLUMN IF NOT EXISTS start_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS end_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS is_popup BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS is_alert_on BOOLEAN DEFAULT false;
